#Pet Adoption API

openapi: 3.0.3
info:
  title: Pet Adoption API
  description: >
    This API powers a web-based pet adoption system. It allows users to view animals,
    submit adoption applications, manage appointments, view medical records, and handle
    staff and user accounts.
  version: "1.3"

tags:
  - name: animals
    description: Endpoints related to animals available for adoption
  - name: adopters
    description: Endpoints related to adopters/applicants
  - name: adoption applications
    description: Endpoints for managing adoption applications
  - name: appointments
    description: Endpoints for managing visit appointments
  - name: medical records
    description: Endpoints for managing medical records of animals
  - name: staff
    description: Endpoints for staff management
  - name: users
    description: Endpoints for user accounts and authentication

paths:


  # ANIMALS #

  /animals:
    get:
      summary: Retrieve all animals
      tags: [animals]
      responses:
        200:
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Animal"
    post:
      summary: Add a new animal
      tags: [animals]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnimalCreate"
      responses:
        201:
          description: Animal successfully added
        400:
          description: Invalid input

  /animals/{animalId}:
    get:
      summary: Get details of a specific animal
      tags: [animals]
      parameters:
        - name: animalId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Animal details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Animal"
        404:
          description: Animal not found
    patch:
      summary: Update a specific animal
      tags: [animals]
      parameters:
        - name: animalId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnimalUpdate"
      responses:
        200:
          description: Animal successfully updated
        400:
          description: Invalid input
        404:
          description: Animal not found
    delete:
      summary: Delete an animal
      tags: [animals]
      parameters:
        - name: animalId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successfully deleted
        404:
          description: Animal not found



  # ADOPTERS #

  /adopters:
    get:
      summary: Retrieve all adopters
      tags: [adopters]
      responses:
        200:
          description: List of adopters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Adopter"
    post:
      summary: Add a new adopter
      tags: [adopters]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdopterCreate"
      responses:
        201:
          description: Adopter successfully added

  /adopters/{adopterId}:
    get:
      summary: Get adopter details
      tags: [adopters]
      parameters:
        - name: adopterId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Adopter information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Adopter"
        404:
          description: Adopter not found
    patch:
      summary: Update adopter details
      tags: [adopters]
      parameters:
        - name: adopterId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdopterUpdate"
      responses:
        200:
          description: Adopter updated
        404:
          description: Not found
    delete:
      summary: Delete an adopter
      tags: [adopters]
      parameters:
        - name: adopterId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Adopter deleted
        404:
          description: Not found



  # ADOPTION APPLICATIONS #

  /adoption-applications:
    get:
      summary: Retrieve all adoption applications
      tags: [adoption applications]
      responses:
        200:
          description: List of applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Application"
    post:
      summary: Submit a new adoption application
      tags: [adoption applications]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationCreate"
      responses:
        201:
          description: Application successfully created

  /adoption-applications/{applicationId}:
    get:
      summary: Get application details
      tags: [adoption applications]
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Application details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        404:
          description: Not found
    patch:
      summary: Update an application
      tags: [adoption applications]
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationUpdate"
      responses:
        200:
          description: Application updated
        404:
          description: Not found
    delete:
      summary: Delete an application
      tags: [adoption applications]
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Application deleted
        404:
          description: Not found


  # APPOINTMENTS #

  /appointments:
    get:
      summary: Retrieve all appointments
      tags: [appointments]
      responses:
        200:
          description: List of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Appointment"
    post:
      summary: Schedule an appointment
      tags: [appointments]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentCreate"
      responses:
        201:
          description: Appointment scheduled

  /appointments/{appointmentId}:
    get:
      summary: Retrieve appointment details
      tags: [appointments]
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Appointment details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        404:
          description: Not found
    patch:
      summary: Update an appointment
      tags: [appointments]
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentUpdate"
      responses:
        200:
          description: Appointment updated
        404:
          description: Not found
    delete:
      summary: Cancel an appointment
      tags: [appointments]
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Appointment canceled
        404:
          description: Not found


  # MEDICAL RECORDS #

  /medical-records:
    get:
      summary: Retrieve all medical records
      tags: [medical records]
      responses:
        200:
          description: List of medical records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MedicalRecord"
    post:
      summary: Add a new medical record
      tags: [medical records]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MedicalRecordCreate"
      responses:
        201:
          description: Medical record added

  /medical-records/{recordId}:
    get:
      summary: Retrieve medical record details
      tags: [medical records]
      parameters:
        - name: recordId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Medical record details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MedicalRecord"
        404:
          description: Not found


  # STAFF #

  /staff:
    get:
      summary: Retrieve all staff members
      tags: [staff]
      responses:
        200:
          description: Staff list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Staff"
    post:
      summary: Add a staff member
      tags: [staff]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StaffCreate"
      responses:
        201:
          description: Staff member added

  /staff/{staffId}:
    get:
      summary: Retrieve staff details
      tags: [staff]
      parameters:
        - name: staffId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Staff details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Staff"
        404:
          description: Not found


  # USERS & AUTHENTICATION #

  /users:
    get:
      summary: Retrieve all users
      tags: [users]
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Register a new user
      tags: [users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegister"
      responses:
        201:
          description: User registered

  /users/login:
    post:
      summary: Log in a user
      tags: [users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        200:
          description: Login successful
        401:
          description: Invalid credentials

  /users/{userId}:
    get:
      summary: Get user details
      tags: [users]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        404:
          description: Not found


# COMPONENTS #

components:
  schemas:

    # ANIMALS #

    Animal:
      type: object
      properties:
        id: { type: integer, example: 1 }
        name: { type: string, example: "Coco" }
        species: { type: string, example: "Cat" }
        breed: { type: string, example: "Siamese" }
        age: { type: integer, example: 2 }
        gender: { type: string, example: "Female" }
        status: { type: string, example: "Available" }

    AnimalCreate:
      allOf:
        - $ref: "#/components/schemas/Animal"

    AnimalUpdate:
      type: object
      description: Fields allowed to update
      properties:
        name: { type: string }
        breed: { type: string }
        status: { type: string }


    # ADOPTERS #

    Adopter:
      type: object
      properties:
        id: { type: integer, example: 1 }
        name: { type: string, example: "Sierra Madre" }
        email: { type: string, example: "sierramadre@gmail.com" }
        address: { type: string, example: "123 Bolao Street" }
        contactNo: { type: string, example: "09171234567" }

    AdopterCreate:
      allOf:
        - $ref: "#/components/schemas/Adopter"

    AdopterUpdate:
      type: object
      properties:
        name: { type: string }
        address: { type: string }
        contactNo: { type: string }


    # ADOPTION APPLICATIONS #


    Application:
      type: object
      properties:
        id: { type: integer, example: 1 }
        adopterId: { type: integer, example: 12 }
        animalId: { type: integer, example: 5 }
        dateApplied: { type: string, format: date, example: "2025-11-12" }
        status: { type: string, example: "Approved" }

    ApplicationCreate:
      allOf:
        - $ref: "#/components/schemas/Application"

    ApplicationUpdate:
      type: object
      properties:
        status: { type: string }


    # APPOINTMENTS #

    Appointment:
      type: object
      properties:
        id: { type: integer, example: 1 }
        adopterId: { type: integer, example: 12 }
        scheduleDate: { type: string, format: date }
        purpose: { type: string, example: "Finalize an adoption" }
        status: { type: string, example: "Scheduled" }

    AppointmentCreate:
      allOf:
        - $ref: "#/components/schemas/Appointment"

    AppointmentUpdate:
      type: object
      properties:
        scheduleDate: { type: string, format: date }
        status: { type: string }


    # MEDICAL RECORDS #

    MedicalRecord:
      type: object
      properties:
        id: { type: integer }
        animalId: { type: integer }
        recordDate: { type: string, format: date }
        recordType: { type: string, example: "Vaccination" }

    MedicalRecordCreate:
      allOf:
        - $ref: "#/components/schemas/MedicalRecord"


    ############################################
    # STAFF #

    Staff:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        email: { type: string }
        contactNo: { type: string }

    StaffCreate:
      allOf:
        - $ref: "#/components/schemas/Staff"


    # USERS #

    User:
      type: object
      properties:
        id: { type: integer, example: 1 }
        username: { type: string, example: "sierramadre" }
        role: { type: string, example: "admin" }

    UserRegister:
      type: object
      required: [username, password]
      properties:
        username: { type: string }
        password: { type: string, format: password }

    UserLogin:
      type: object
      required: [username, password]
      properties:
        username: { type: string }
        password: { type: string, format: password }